server:
  tomcat:
    uri-encoding: UTF-8
  port: 8080

spring:
  #    hikari:
  #      connection-timeout: 30000
  #      maximum-pool-size: 3
  #      max-lifetime: 580000
  #      pool-name: Hikari
  #      read-only: false
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl # 테이블 대문자
---
spring:
  config:
    activate:
      on-profile: local
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
#    properties:
#      hibernate:
#        format_sql: false
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test # 테스트용 인메모리 DB
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console

---
#spring:
#  config:
#    activate:

#      on-profile: dev